import image1 from "../Code-img/animea.webp"
import image11 from "../Code-img/animea1.webp"
import image2 from "../Code-img/an.webp"
import image22 from "../Code-img/an1.webp"
import image3 from "../Code-img/gym.webp"
import image33 from "../Code-img/gym1.webp"
import image4 from "../Code-img/hack.webp"
import image44 from "../Code-img/hack2.webp"
import image5 from "../Code-img/life.webp"
import image55 from "../Code-img/life1.webp"
import image6 from "../Code-img/m.webp"
import image66 from "../Code-img/m1.webp"
import image111 from "../Code-img/cn3.webp"
const CapsData = [
    {
        id: 1,
        image1: `${image1}`,
        image2: `${image11}`,
        productname: "Cap",
        productbas: "Pack Of Five Plain C...",
        calagiry:"Anime",
        price: 549,
        size:"L",
        image3: `${image111}`,
        dellogo: "CodesWear",
        Pack: "Pack Of Five Plain Cap (L/Black)",
        description: "Product Description:",
        pera: "Elevate your style and protect yourself from the sun with the Pack Of Five Plain Cap. This versatile pack includes five high-quality caps in classic and neutral colors. Each cap is designed for comfort and functionality, making them perfect for various occasions. The caps are made from durable and breathable materials, ensuring a comfortable fit during hot days. With their adjustable strap closure, these caps can be customized to fit your head perfectly. The plain and minimalist design makes them easy to pair with a wide range of outfits, from casual to sporty. Whether you're heading to the beach, going for a run, or simply want to add a stylish touch to your ensemble, these caps have got you covered. Protect your face from the sun's rays and add a finishing touch to your look with the Pack Of Five Plain Cap",
        highlights: "Product Highlights:",
        hone: "Includes a pack of five high-quality plain caps",
        htwo: "Made from durable and breathable materials",
        hthree: "Adjustable strap closure for a customized fit",
        hfour: "Classic and versatile design suitable for various occasions",
        hfive: "Perfect for sun protection and adding style to your outfit",
        tags: "Tags: plain cap, pack of five, versatile, sun protection, classic design, adjustable strap",
        color: "Black",
        lastprice:"₹699" ,
        btn1: "Buy Now",
        btn2: "Add to Cart",
        Exciting: "Exciting Offers:",
        litagcom1: "Get Flat 10% off on all prepaid orders above ₹249 Use coupon CODESWEAR10",
        litagcom2: "Get Customized T-Shirts at only ₹549.",
        litagcom3: "Buy 2 get 1 Free and buy 3 get 2 Free on all Caps - Prepaid orders only.",
        litagcom4: "Buy 2 get 1 Free and buy 3 get 2 Free on all Mousepads - Prepaid orders only."
    },
    {
        id: 2,
        image1: `${image2}`,
        image2: `${image22}`,
        productname: "Cap",
        productbas: "Pack Of Five Plain C...",
        price: 549,
        calagiry:"Coding",
        size:"L",
        image3: `${image3}`,
        dellogo: "CodesWear",
        Pack: "Pack Of Five Plain Cap (L/Black)",
        description: "Product Description:",
        pera: "Elevate your style and protect yourself from the sun with the Pack Of Five Plain Cap. This versatile pack includes five high-quality caps in classic and neutral colors. Each cap is designed for comfort and functionality, making them perfect for various occasions. The caps are made from durable and breathable materials, ensuring a comfortable fit during hot days. With their adjustable strap closure, these caps can be customized to fit your head perfectly. The plain and minimalist design makes them easy to pair with a wide range of outfits, from casual to sporty. Whether you're heading to the beach, going for a run, or simply want to add a stylish touch to your ensemble, these caps have got you covered. Protect your face from the sun's rays and add a finishing touch to your look with the Pack Of Five Plain Cap",
        highlights: "Product Highlights:",
        hone: "Includes a pack of five high-quality plain caps",
        htwo: "Made from durable and breathable materials",
        hthree: "Adjustable strap closure for a customized fit",
        hfour: "Classic and versatile design suitable for various occasions",
        hfive: "Perfect for sun protection and adding style to your outfit",
        tags: "Tags: plain cap, pack of five, versatile, sun protection, classic design, adjustable strap",
        color: "Black",
        lastprice:"₹699" ,
        btn1: "Buy Now",
        btn2: "Add to Cart",
        Exciting: "Exciting Offers:",
        litagcom1: "Get Flat 10% off on all prepaid orders above ₹249 Use coupon CODESWEAR10",
        litagcom2: "Get Customized T-Shirts at only ₹549.",
        litagcom3: "Buy 2 get 1 Free and buy 3 get 2 Free on all Caps - Prepaid orders only.",
        litagcom4: "Buy 2 get 1 Free and buy 3 get 2 Free on all Mousepads - Prepaid orders only."
    },
    {
        id: 3,
        image1: `${image3}`,
        image2: `${image33}`,
        productname: "Cap",
        productbas: "Pack Of Five Anonymo...",
        price: 549,
        size:"L",
        image3: `${image3}`,
        dellogo: "CodesWear",
        Pack: "Pack Of Five Plain Cap (L/Black)",
        description: "Product Description:",
        pera: "Elevate your style and protect yourself from the sun with the Pack Of Five Plain Cap. This versatile pack includes five high-quality caps in classic and neutral colors. Each cap is designed for comfort and functionality, making them perfect for various occasions. The caps are made from durable and breathable materials, ensuring a comfortable fit during hot days. With their adjustable strap closure, these caps can be customized to fit your head perfectly. The plain and minimalist design makes them easy to pair with a wide range of outfits, from casual to sporty. Whether you're heading to the beach, going for a run, or simply want to add a stylish touch to your ensemble, these caps have got you covered. Protect your face from the sun's rays and add a finishing touch to your look with the Pack Of Five Plain Cap",
        highlights: "Product Highlights:",
        hone: "Includes a pack of five high-quality plain caps",
        htwo: "Made from durable and breathable materials",
        hthree: "Adjustable strap closure for a customized fit",
        hfour: "Classic and versatile design suitable for various occasions",
        hfive: "Perfect for sun protection and adding style to your outfit",
        tags: "Tags: plain cap, pack of five, versatile, sun protection, classic design, adjustable strap",
        color: "Black",
        lastprice:"₹699" ,
        btn1: "Buy Now",
        btn2: "Add to Cart",
        Exciting: "Exciting Offers:",
        litagcom1: "Get Flat 10% off on all prepaid orders above ₹249 Use coupon CODESWEAR10",
        litagcom2: "Get Customized T-Shirts at only ₹549.",
        litagcom3: "Buy 2 get 1 Free and buy 3 get 2 Free on all Caps - Prepaid orders only.",
        litagcom4: "Buy 2 get 1 Free and buy 3 get 2 Free on all Mousepads - Prepaid orders only."
    },
    {
        id: 4,
        image1: `${image4}`,
        image2: `${image44}`,
        productname: "Cap",
        productbas: "Pack Of Three Anonym...",
        price: 549,
        size:"L",
        image3: `${image3}`,
        dellogo: "CodesWear",
        Pack: "Pack Of Five Plain Cap (L/Black)",
        description: "Product Description:",
        pera: "Elevate your style and protect yourself from the sun with the Pack Of Five Plain Cap. This versatile pack includes five high-quality caps in classic and neutral colors. Each cap is designed for comfort and functionality, making them perfect for various occasions. The caps are made from durable and breathable materials, ensuring a comfortable fit during hot days. With their adjustable strap closure, these caps can be customized to fit your head perfectly. The plain and minimalist design makes them easy to pair with a wide range of outfits, from casual to sporty. Whether you're heading to the beach, going for a run, or simply want to add a stylish touch to your ensemble, these caps have got you covered. Protect your face from the sun's rays and add a finishing touch to your look with the Pack Of Five Plain Cap",
        highlights: "Product Highlights:",
        hone: "Includes a pack of five high-quality plain caps",
        htwo: "Made from durable and breathable materials",
        hthree: "Adjustable strap closure for a customized fit",
        hfour: "Classic and versatile design suitable for various occasions",
        hfive: "Perfect for sun protection and adding style to your outfit",
        tags: "Tags: plain cap, pack of five, versatile, sun protection, classic design, adjustable strap",
        color: "Black",
        lastprice:"₹699" ,
        btn1: "Buy Now",
        btn2: "Add to Cart",
        Exciting: "Exciting Offers:",
        litagcom1: "Get Flat 10% off on all prepaid orders above ₹249 Use coupon CODESWEAR10",
        litagcom2: "Get Customized T-Shirts at only ₹549.",
        litagcom3: "Buy 2 get 1 Free and buy 3 get 2 Free on all Caps - Prepaid orders only.",
        litagcom4: "Buy 2 get 1 Free and buy 3 get 2 Free on all Mousepads - Prepaid orders only."
    },
    {
        id: 5,
        image1: `${image5}`,
        image2: `${image55}`,
        productname: "Cap",
        productbas: "Naruto Cap...",
        price: 549,
        size:"L",
        image3: `${image3}`,
        dellogo: "CodesWear",
        Pack: "Pack Of Five Plain Cap (L/Black)",
        description: "Product Description:",
        pera: "Elevate your style and protect yourself from the sun with the Pack Of Five Plain Cap. This versatile pack includes five high-quality caps in classic and neutral colors. Each cap is designed for comfort and functionality, making them perfect for various occasions. The caps are made from durable and breathable materials, ensuring a comfortable fit during hot days. With their adjustable strap closure, these caps can be customized to fit your head perfectly. The plain and minimalist design makes them easy to pair with a wide range of outfits, from casual to sporty. Whether you're heading to the beach, going for a run, or simply want to add a stylish touch to your ensemble, these caps have got you covered. Protect your face from the sun's rays and add a finishing touch to your look with the Pack Of Five Plain Cap",
        highlights: "Product Highlights:",
        hone: "Includes a pack of five high-quality plain caps",
        htwo: "Made from durable and breathable materials",
        hthree: "Adjustable strap closure for a customized fit",
        hfour: "Classic and versatile design suitable for various occasions",
        hfive: "Perfect for sun protection and adding style to your outfit",
        tags: "Tags: plain cap, pack of five, versatile, sun protection, classic design, adjustable strap",
        color: "Black",
        lastprice:"₹699" ,
        btn1: "Buy Now",
        btn2: "Add to Cart",
        Exciting: "Exciting Offers:",
        litagcom1: "Get Flat 10% off on all prepaid orders above ₹249 Use coupon CODESWEAR10",
        litagcom2: "Get Customized T-Shirts at only ₹549.",
        litagcom3: "Buy 2 get 1 Free and buy 3 get 2 Free on all Caps - Prepaid orders only.",
        litagcom4: "Buy 2 get 1 Free and buy 3 get 2 Free on all Mousepads - Prepaid orders only."
    },
    {
        id: 6,
        image1: `${image6}`,
        image2: `${image66}`,
        productname: "Cap",
        productbas: "Marshmallow Cap...",
        price: 549,
        size:"L",
        image3: `${image3}`,
        dellogo: "CodesWear",
        Pack: "Pack Of Five Plain Cap (L/Black)",
        description: "Product Description:",
        pera: "Elevate your style and protect yourself from the sun with the Pack Of Five Plain Cap. This versatile pack includes five high-quality caps in classic and neutral colors. Each cap is designed for comfort and functionality, making them perfect for various occasions. The caps are made from durable and breathable materials, ensuring a comfortable fit during hot days. With their adjustable strap closure, these caps can be customized to fit your head perfectly. The plain and minimalist design makes them easy to pair with a wide range of outfits, from casual to sporty. Whether you're heading to the beach, going for a run, or simply want to add a stylish touch to your ensemble, these caps have got you covered. Protect your face from the sun's rays and add a finishing touch to your look with the Pack Of Five Plain Cap",
        highlights: "Product Highlights:",
        hone: "Includes a pack of five high-quality plain caps",
        htwo: "Made from durable and breathable materials",
        hthree: "Adjustable strap closure for a customized fit",
        hfour: "Classic and versatile design suitable for various occasions",
        hfive: "Perfect for sun protection and adding style to your outfit",
        tags: "Tags: plain cap, pack of five, versatile, sun protection, classic design, adjustable strap",
        color: "Black",
        lastprice:"₹699" ,
        btn1: "Buy Now",
        btn2: "Add to Cart",
        Exciting: "Exciting Offers:",
        litagcom1: "Get Flat 10% off on all prepaid orders above ₹249 Use coupon CODESWEAR10",
        litagcom2: "Get Customized T-Shirts at only ₹549.",
        litagcom3: "Buy 2 get 1 Free and buy 3 get 2 Free on all Caps - Prepaid orders only.",
        litagcom4: "Buy 2 get 1 Free and buy 3 get 2 Free on all Mousepads - Prepaid orders only."
    },
    {
        id: 7,
        image1: `${image3}`,
        image2: `${image44}`,
        productname: "Cap",
        productbas: "Anonymous Hacker...",
        price: 549,
        size:"L",
        image3: `${image3}`,
        dellogo: "CodesWear",
        Pack: "Pack Of Five Plain Cap (L/Black)",
        description: "Product Description:",
        pera: "Elevate your style and protect yourself from the sun with the Pack Of Five Plain Cap. This versatile pack includes five high-quality caps in classic and neutral colors. Each cap is designed for comfort and functionality, making them perfect for various occasions. The caps are made from durable and breathable materials, ensuring a comfortable fit during hot days. With their adjustable strap closure, these caps can be customized to fit your head perfectly. The plain and minimalist design makes them easy to pair with a wide range of outfits, from casual to sporty. Whether you're heading to the beach, going for a run, or simply want to add a stylish touch to your ensemble, these caps have got you covered. Protect your face from the sun's rays and add a finishing touch to your look with the Pack Of Five Plain Cap",
        highlights: "Product Highlights:",
        hone: "Includes a pack of five high-quality plain caps",
        htwo: "Made from durable and breathable materials",
        hthree: "Adjustable strap closure for a customized fit",
        hfour: "Classic and versatile design suitable for various occasions",
        hfive: "Perfect for sun protection and adding style to your outfit",
        tags: "Tags: plain cap, pack of five, versatile, sun protection, classic design, adjustable strap",
        color: "Black",
        lastprice:"₹699" ,
        btn1: "Buy Now",
        btn2: "Add to Cart",
        Exciting: "Exciting Offers:",
        litagcom1: "Get Flat 10% off on all prepaid orders above ₹249 Use coupon CODESWEAR10",
        litagcom2: "Get Customized T-Shirts at only ₹549.",
        litagcom3: "Buy 2 get 1 Free and buy 3 get 2 Free on all Caps - Prepaid orders only.",
        litagcom4: "Buy 2 get 1 Free and buy 3 get 2 Free on all Mousepads - Prepaid orders only."
    },
    {
        id: 8,
        image1: `${image6}`,
        image2: `${image1}`,
        productname: "Cap",
        productbas: "Git Cap...",
        price: 549,
        size:"L",
        image3: `${image3}`,
        dellogo: "CodesWear",
        Pack: "Pack Of Five Plain Cap (L/Black)",
        description: "Product Description:",
        pera: "Elevate your style and protect yourself from the sun with the Pack Of Five Plain Cap. This versatile pack includes five high-quality caps in classic and neutral colors. Each cap is designed for comfort and functionality, making them perfect for various occasions. The caps are made from durable and breathable materials, ensuring a comfortable fit during hot days. With their adjustable strap closure, these caps can be customized to fit your head perfectly. The plain and minimalist design makes them easy to pair with a wide range of outfits, from casual to sporty. Whether you're heading to the beach, going for a run, or simply want to add a stylish touch to your ensemble, these caps have got you covered. Protect your face from the sun's rays and add a finishing touch to your look with the Pack Of Five Plain Cap",
        highlights: "Product Highlights:",
        hone: "Includes a pack of five high-quality plain caps",
        htwo: "Made from durable and breathable materials",
        hthree: "Adjustable strap closure for a customized fit",
        hfour: "Classic and versatile design suitable for various occasions",
        hfive: "Perfect for sun protection and adding style to your outfit",
        tags: "Tags: plain cap, pack of five, versatile, sun protection, classic design, adjustable strap",
        color: "Black",
        lastprice:"₹699" ,
        btn1: "Buy Now",
        btn2: "Add to Cart",
        Exciting: "Exciting Offers:",
        litagcom1: "Get Flat 10% off on all prepaid orders above ₹249 Use coupon CODESWEAR10",
        litagcom2: "Get Customized T-Shirts at only ₹549.",
        litagcom3: "Buy 2 get 1 Free and buy 3 get 2 Free on all Caps - Prepaid orders only.",
        litagcom4: "Buy 2 get 1 Free and buy 3 get 2 Free on all Mousepads - Prepaid orders only."
    },
    {
        id: 9,
        image1: `${image3}`,
        image2: `${image2}`,
        productname: "Cap",
        productbas: "Adobe After Effects ...",
        price: 549,
        size:"L",
        image3: `${image3}`,
        dellogo: "CodesWear",
        Pack: "Pack Of Five Plain Cap (L/Black)",
        description: "Product Description:",
        pera: "Elevate your style and protect yourself from the sun with the Pack Of Five Plain Cap. This versatile pack includes five high-quality caps in classic and neutral colors. Each cap is designed for comfort and functionality, making them perfect for various occasions. The caps are made from durable and breathable materials, ensuring a comfortable fit during hot days. With their adjustable strap closure, these caps can be customized to fit your head perfectly. The plain and minimalist design makes them easy to pair with a wide range of outfits, from casual to sporty. Whether you're heading to the beach, going for a run, or simply want to add a stylish touch to your ensemble, these caps have got you covered. Protect your face from the sun's rays and add a finishing touch to your look with the Pack Of Five Plain Cap",
        highlights: "Product Highlights:",
        hone: "Includes a pack of five high-quality plain caps",
        htwo: "Made from durable and breathable materials",
        hthree: "Adjustable strap closure for a customized fit",
        hfour: "Classic and versatile design suitable for various occasions",
        hfive: "Perfect for sun protection and adding style to your outfit",
        tags: "Tags: plain cap, pack of five, versatile, sun protection, classic design, adjustable strap",
        color: "Black",
        lastprice:"₹699" ,
        btn1: "Buy Now",
        btn2: "Add to Cart",
        Exciting: "Exciting Offers:",
        litagcom1: "Get Flat 10% off on all prepaid orders above ₹249 Use coupon CODESWEAR10",
        litagcom2: "Get Customized T-Shirts at only ₹549.",
        litagcom3: "Buy 2 get 1 Free and buy 3 get 2 Free on all Caps - Prepaid orders only.",
        litagcom4: "Buy 2 get 1 Free and buy 3 get 2 Free on all Mousepads - Prepaid orders only."
    },
    {
        id: 10,
        image1: `${image5}`,
        image2: `${image33}`,
        productname: "Cap",
        productbas: "Pack  C...",
        price: 549,
        size:"L",
        image3: `${image3}`,
        dellogo: "CodesWear",
        Pack: "Pack Of Five Plain Cap (L/Black)",
        description: "Product Description:",
        pera: "Elevate your style and protect yourself from the sun with the Pack Of Five Plain Cap. This versatile pack includes five high-quality caps in classic and neutral colors. Each cap is designed for comfort and functionality, making them perfect for various occasions. The caps are made from durable and breathable materials, ensuring a comfortable fit during hot days. With their adjustable strap closure, these caps can be customized to fit your head perfectly. The plain and minimalist design makes them easy to pair with a wide range of outfits, from casual to sporty. Whether you're heading to the beach, going for a run, or simply want to add a stylish touch to your ensemble, these caps have got you covered. Protect your face from the sun's rays and add a finishing touch to your look with the Pack Of Five Plain Cap",
        highlights: "Product Highlights:",
        hone: "Includes a pack of five high-quality plain caps",
        htwo: "Made from durable and breathable materials",
        hthree: "Adjustable strap closure for a customized fit",
        hfour: "Classic and versatile design suitable for various occasions",
        hfive: "Perfect for sun protection and adding style to your outfit",
        tags: "Tags: plain cap, pack of five, versatile, sun protection, classic design, adjustable strap",
        color: "Black",
        lastprice:"₹699" ,
        btn1: "Buy Now",
        btn2: "Add to Cart",
        Exciting: "Exciting Offers:",
        litagcom1: "Get Flat 10% off on all prepaid orders above ₹249 Use coupon CODESWEAR10",
        litagcom2: "Get Customized T-Shirts at only ₹549.",
        litagcom3: "Buy 2 get 1 Free and buy 3 get 2 Free on all Caps - Prepaid orders only.",
        litagcom4: "Buy 2 get 1 Free and buy 3 get 2 Free on all Mousepads - Prepaid orders only."
    },

]

export { CapsData };